name: CI

on:
    push:
    pull_request:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-go@v2
                with:
                    go-version: '^1.17'
            -   name: Run tests
                run: make test

    coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-go@v2
                with:
                    go-version: '^1.17'
            -   name: Generate Code Coverage
                run: make coverage
            -   name: Send coverage
                uses: shogo82148/actions-goveralls@v1
                with:
                    path-to-profile: coverage.cov

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v2
