name: Release

on:
    push:
        tags:
            - v*

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   uses: actions/setup-go@v2
            -   name: GoReleaser
                uses: goreleaser/goreleaser-action@v2
                with:
                    args: release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
